pipelines:
  - name: pipeline_S_Bash_0540
    steps:
      - name: S_Bash_0540
        type: Bash
        configuration:
          nodePool: c7dynamic
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - 1.15.2
        execution:
          onExecute:
            - |
              [[ "$step_image_name:$step_image_tag" == "releases-docker.jfrog.io/jfrog/pipelines-c7go:1.15.2" ]]
            - source /root/.gvm/scripts/gvm
            - gvm list
            - docker images
            - echo "$step_image_tag"
            - gvm use 1.15
            - |
              [[ "$(go version)" == *"$step_image_tag"* ]]
              
