resources:
  - name: valueStore
    type: PropertyBag
    configuration:
      key: value
      foo: bar
pipelines:
  - name: testJenkinsOR
    steps:
      - name: bashStep
        type: Bash 
#         outputResources:
#           - name: valueStore
        configuration:
          inputResources:
            - name: valueStore
        execution:
          onStart:
            - echo "executing onStart"
      - name: jenkinsStep
        type: Jenkins
        configuration:
          outputResources:
            - name: valueStore
          jenkinsJobName: testPipeline
          integrations:
            - name: jenkins
#         execution:
#           onSuccess:
#             - write_output valueStore "foo=bar"
