resources:
  - name: valueStore
    type: PropertyBag
    configuration:
      key: value
      foo: bar
pipelines:
  - name: testPipelinesOR
    steps:
      - name: jenkinsStep 
        type: Jenkins
        configuration:
          outputResources:
            - name: valueStore
          jenkinsJobName: testPipelineOR
          integrations:
            - name: jenkins
