resources:
  - name: valueStore
    type: PropertyBag
    configuration:
      key: value
      foo: bar
pipelines:
  - name: testJenkins
    steps:
      - name: bashStep
        type: Bash 
        outputResources:
          - name: valueStore
        execution:
          onStart:
            - echo "executing onStart"
          #onExecute:
           # - write_output valueStore key:value
      - name: jenkinsStep
        type: Jenkins
        configuration:
          inputSteps:
            - name: bashStep
          inputResources:
            - name: valueStore
          jenkinsJobName: testPipeline
          integrations:
            - name: jenkins
