
resources:
  - name: S_HelmPublish_5933_029_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: neha-mishraa/ORpipelines
      branches:
        include: {{gitBranch}}
  - name: S_HelmPublish_5933_029_HelmChart
    type: HelmChart
    configuration:
      sourceArtifactory: s_artifactory
      repository: test-automation-helm-local
      version: version
      chart: chart

pipelines:
  - name: pipeline_S_HelmPublish_5933_029
    configuration:
      environmentVariables:
        readOnly:
          CHART_VERSION: v0.5933029.${run_id}
    steps:
      - name: S_HelmPublish_5933_029_1
        type: HelmPublish
        configuration:
          helmVersion: 3
          chartPath: "./tests/helmCharts/myChart"
          flags: "--version ${CHART_VERSION}"
          inputResources:
            - name: S_HelmPublish_5933_029_GitRepo
          outputResources:
            - name: S_HelmPublish_5933_029_HelmChart
          integrations:
            - name: s_artifactory
        execution:
          onStart:
            - replace_envs ${res_S_HelmPublish_5933_029_GitRepo_resourcePath}/tests/helmCharts/myChart/Chart.yaml
            - helm3 version
            # - helm version
            
      - name: S_HelmPublish_5933_029_2
        type: Bash
        configuration:
          inputResources:
            - name: S_HelmPublish_5933_029_HelmChart
        execution:
          onExecute:
            - if [ "$res_S_HelmPublish_5933_029_HelmChart_version" != "$CHART_VERSION" ]; then return 1; fi
